SPACESHIP_TIME_SHOW=true
SPACESHIP_USER_SHOW=always
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_RPROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_SEPARATE_LINE=false
SPACESHIP_RPROMPT_SEPARATE_LINE=false

SPACESHIP_PROMPT_ORDER=(
    user
    host
    dir
    git
    char
)
#SPACESHIP_RPROMPT_ORDER=(
#    exec_time
#    time
#)
