vim.pack.add({ "https://github.com/ibhagwan/fzf-lua" })

local fzf = require("fzf-lua")

fzf.setup({})
fzf.register_ui_select()

vim.keymap.set("n", "<leader>ff", fzf.files)
vim.keymap.set("n", "<leader>fg", fzf.live_grep)
vim.keymap.set("n", "<leader>fb", fzf.buffers)
vim.keymap.set("n", "<leader>fr", fzf.oldfiles)
vim.keymap.set("n", "<leader>fh", fzf.help_tags)
vim.keymap.set("n", "<leader>fk", fzf.keymaps)
vim.keymap.set("n", "<leader>fc", fzf.commands)
vim.keymap.set("n", "<leader>fd", fzf.diagnostics_document)
vim.keymap.set("n", "<leader>fw", fzf.grep_cword)
vim.keymap.set("n", "<leader>fW", fzf.grep_cWORD)
vim.keymap.set("n", "<leader>/", fzf.blines)
vim.keymap.set("n", "<leader>f/", function()
	fzf.live_grep({ grep_open_files = true })
end)
